### PR TITLE
Update render.js to reduce CPU usage

### PR DESCRIPTION
**Pull request by OpenSourceAnarchist**
I am once again asking to merge 🙏 😄 

Should address your comments, let me know if I can fix anything before closing... I really want to reduce the CPU usage!!

Oh and run minify :)

### CODE REVIEW

**Comment by OpenSourceAnarchist** [comment]
Just in case you don't like the waveforms not clearing all the way, I fixed that too. Just seems unnecessary but it works perfectly now.

In `render.js`
```
if (!this.renderBool || !this.synth.voicesAmount && this.frameTimeStart && document.getElementById("midi_output_selector")?.value == -1) {
    if (auto) {
        if (this.renderAnalysers && !this.synth.highPerformanceMode) {
            // draw the individual analysers until they're clear, hopefully!
            const endTime = Date.now() + 250; // 250 ms
            const intervalId = setInterval(() => {
                if (Date.now() >= endTime) {
                    clearInterval(intervalId);
                } else {
                    this.renderWaveforms();;
                }
            });
        }
        requestAnimationFrame(this.render.bind(this));
    }
    return;
}
```

**Comment by OpenSourceAnarchist** [comment]
I tried to address everything. I still can't reproduce your waveform behavior... it goes to 0 under every condition and file I've tested, along with real-time input. I don't have access to MIDI in, so do test if that bug is happening. And if you still get frozen waveforms, personally I think it's a cool look but if you don't want it please try changing `if (!this.renderBool || this.hasRendered > 1)` to a higher value, e.g. `if (!this.renderBool || this.hasRendered > 20)` and see if it helps. I can't fix it if I don't know why it's happening.

**Comment by OpenSourceAnarchist** [comment]
It's ready again for your review at some point. I truly tried to fix all the issues, but I already know you're going to tell me not to do `this.voiceMeterText = document.querySelector('div.voice_meter.main_controller_element:not(.editable)');`

Yes I know it is pretty hacky, but I've spent a few hours now painstakingly trying to learn how to debug JS and locally sum up all the voices through variations of `let totalCurrentVoices = this.synth.voicesAmount` and looping over all the channels and adding each voice amount to the total. This version just grabs the always-correct value from the master voice meter text. For some reason, it just always works and ensures the waveforms are correctly rendered, no more timing hacks or waiting an arbitrary number of render() calls.

You seem to have more opinions about this than me, so I will edit anything you don't want to experiment around with unless it requires a lot more troubleshooting on my end. I'm more than happy to run these changes on my own `render()` method for my tuning player frontend. But I really don't see why we can't make this work so everyone can benefit :)

**Comment by OpenSourceAnarchist** [comment]
Still having issues rendering falling notes, _however_ I think it's because you're computing `noteFallingTimeMs` in `compute_note_positions.js` correctly. It shouldn't be static all the time, but it's never updated once a Renderer is constructed. Theoretically, it should be dynamically updated whenever a note is first on the user's screen, at the top of the canvas. Instead, it's only at note on. So this has the effect that `notesOnScreen` is always wrong, because it's not the actual number of notes on screen! If you could update `compute_note_positions.js` to compute this based on the canvas height, playback rate, note time, current time, etc. the math should be pretty simple unless there's an even easier way to do it.

I've been banging my head wondering why `notesOnScreen` is wrong, and this is the culprit, which messes up my hasRendered check!

**Comment by spessasus** [comment]
> Still having issues rendering falling notes, _however_ I think it's because you're computing `noteFallingTimeMs` in `compute_note_positions.js` incorrectly. It shouldn't be static all the time, but it's never updated once a Renderer is constructed. Theoretically, it should be dynamically updated whenever a note is first on the user's screen, at the top of the canvas. Instead, it's only at note on. So this has the effect that `notesOnScreen` is always wrong, because it's not the actual number of notes on screen! If you could update `compute_note_positions.js` to compute this based on the canvas height, playback rate, note time, current time, etc. the math should be pretty simple unless there's an even easier way to do it.
> 
> I've been banging my head wondering why `notesOnScreen` is wrong, and this is the culprit, which messes up my hasRendered check!

I honestly have no idea what you're talking about. `computeNotePositions` runs every frame and recomputes everything every frame too. If setting it as a prototype for the Renderer class is confusing to you, it's just a way to split a JavaScript class into multiple files. You can think of it like C#'s `partial class` keyword.

Though I've noticed that I've left a console log in the render method. Whoops!

**Comment by OpenSourceAnarchist** [comment]
Well, it doesn't matter anymore. I finally figured out a solution. Just checking the length of `notesToDraw` fixed the timing issue. Sorry I wasn't clear on what was happening.

In essence, you aren't computing the actual time a note shows up on screen. `notesOnScreen` is only the number of active notes. That confused me for a long time.

I am very sorry, but I am manually editing the files on GitHub myself. My "dev environment" is a local download of the repo, so I can manually upload all the changed files from running minify_website.sh but I think it's easier for you to do it I imagine. Plus, it only matters if you accept the changes :/

I can safely say the last commit 38r3a08 "I figured out a solution" fixes every single issue I've had and passes all my stress tests with live input, notes falling, pausing, resuming, and the waveforms always rendering correctly. If it passes your tests too, I'm sorry to make you run minify but I do hope it saves some CPU cycles for all the demo sites.

**Comment by spessasus** [comment]
Hi,
I've looked at your implementation and there a few two things that look strangr:
1. Why use other html elements when the renderer has access to both synth and sequencer?
2. The notes keep being rendered when the sequencer is paused.
3. Generally the idea is bad. Using the select element to check if the notes are playing to a MIDI out is an okay way to handle this, but what about playing to a Web MIDI Link? The simplest solution (that I've used) is to just check if the sequencer is paused or undefined (then there are no notes so if no voices we can skip)

I've addressed these issues with my own soluton (that's now live).
So since i've fixed this myself, I'm closing this PR. No hard feelings, though! Thanks for the idea and a proposed solution :-)

I hope this will improve the performance like you wanted.

**Comment by OpenSourceAnarchist** [comment]
I'm sitting here laughing at how simple the solution was... I don't know why I thought all the extra conditional checks were necessary, or that I had to wait an extra render cycle (which was the whole reason for `hasRendered`). At least I learned a lot about JavaScript. If only I realized all my conditionals reduced to when the seq was undefined or paused. So obvious! Thank you for all your help and it absolutely improved the performance, even better than mine so I'm glad you didn't use my version.

The reason I used html elements though is because I didn't think to just check the sequencer for being undefined or paused. I thought that wouldn't allow the waveforms to completely render all the voices (if there was reverb, e.g. voices playing a little after the sequencer was paused). Getting the values from the sequencer and synth was unreliable, as in the values weren't matching up with the html elements. For `notesOnScreen`, this is because of the reason I stated in a previous comment. For the voices, I tried very hard to match your code to compute the number of voices in the voice meter but I couldn't so I just grabbed the value directly from the html element. In hindsight this was completely unnecessary because like you said, we just need to check if it's undefined or paused apparently.

Thanks again, and I'm almost done with "DynaTune", stay _tuned_ :))

**Pull request closed without merging**
