### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by davy7125**
The translation is completed but I couldn't test locally. My turn to have build issues!
"esbuild not installed" when I try to minify it with your script. So I installed npm and then ran
`npm install esbuild`
but I still have the error.

Maybe you can quickly test the new translation on your side and if no bugs are introduced put it online? I'll then fix any possible typos.

### CODE REVIEW

**Comment by spessasus** [comment]
Hi Davy,

First of all, thanks so much for this! I've also sent the Polyphone's polish translation to the mail address provided on the website.

Secondly, you're right, I forgot to mention that for minifying you need to install `esbuild` *globally* i.e. `npm install -g esbuild` and then it should work fine. (if you're on linux, npm may ask for sudo)

Lastly, I compiled the branch and I see the following:
image
The `&nbsp;` is parsed as text because all of the values are set as `textContent` rather than `innerHTML`. If you can fix it, then it will be great!

**Comment by davy7125** [comment]
I removed all special chars except one: the new lines "&#013;"
It can be seen when hovering the compress option button in the soundfont export

**Comment by spessasus** [comment]
> I removed all special chars except one: the new lines `&#013;` It can be seen when hovering the compress option button in the soundfont export

Thanks! Though,
image

Using regular `\n` instead makes the line breaks appear correctly. Could you please tweak the PR? After that I'll merge it because I don't see any typos.

**Comment by davy7125** [comment]
`\n` is now used

**Review by spessasus — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
