### PR TITLE
[feature] 99% Brazilian Portuguese translation for Website

### PR DESCRIPTION
**Pull request by lucmsilva651**
Hi! As the title says, I have managed to translate everything to Brazilian Portuguese.

But one question: I have put everything needed on locale.js but my language still doesn't show up on the menu. I am doing it wrong? Feel free to request changes, as long as you explain everything.

Also, I have deleted the .idea folder as it's on .gitignore. So, if you don't want to merge that commit, feel free to ignore it.

As always, I am here to help.

~ Lucas ;)

### CODE REVIEW

**Comment by spessasus** [comment]
Hi,

Thanks for translating Spessasynth! I really appreciate it :)

For your language to show up, you need to **minify the JavaScript.** The instructions are in `src/README.md`. I forgot to mention it in the translation guide, sorry! After compiling it should show up correctly.

As for .idea, I never noticed that it was in gitignore, but if you can, please restore it back. I'll remove it from gitignore later.

Other than that, LGTM.

**Review by spessasus — CHANGES_REQUESTED** [review]
As mentioned in my comment, a minification and restoration of .idea folder is needed.

**Review by spessasus — APPROVED** [review]
I've changed those myself and added you to the translation credits in readme.
Thanks again for this translation!

**Comment by lucmsilva651** [comment]
> I've changed those myself and added you to the translation credits in readme. Thanks again for this translation!

Hi! I am sorry for not doing anything yet; and also, thank you for doing that for me. I was very busy, and I've only read your replies rn...

Anyways, ty for anything.

~ Lucas ;)

**Pull request merged**
